apiVersion: v1
kind: Service
metadata:
  name: prometheus-dashboard
  namespace: monitor
spec:
  type: NodePort
  ports:
  - name: port-1
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: port-2
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard
  namespace: monitor
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana