apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: monitor
spec:
  interval: 2m # Check for changes every 2 minutes
  url: https://prometheus-community.github.io/helm-charts