apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: xbsc-alerts
  namespace: default
spec:
  summary: "[DEV] XPC Services & Capabilties GitOps Notification"
  eventSeverity: info