apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 2m # Check for changes every 2 minutes
  url:  https://kiali.org/helm-charts