apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:  
  dependsOn:
    - name: flux-notification
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./networking/development
  prune: true
  wait: true
  #suspend: true