apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: "1.24.2"
      interval: 1h # Check for new chart
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: istiod
  interval: 10m # Check for cluster drift
  targetNamespace: istio-system