apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
      chart: gateway
      version: "1.24.2"
      interval: 1h # Check for new chart version
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: istio-ingress 
  targetNamespace: istio-ingress
  interval: 10m # Check for cluster drift
  values:
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    service:
      type: LoadBalancer