apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      version: "1.24.2"
      interval: 1h # Check for new chart 
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: istio-base
  targetNamespace: istio-system
  interval: 10m # Check for cluster drift
  values:
    defaultRevision: default