apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - namespace.yaml
  - repository.yaml  
  - istio-base-release.yaml
  - istio-d-release.yaml
  - istio-gateway-release.yaml